config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "flights#new"

  resources :flights
  resources :bookings, only:[:index, :new, :create, :show]
end

app/models/airport.rb
class Airport < ApplicationRecord
	has_many :departing_flights, foreign_key: "departure_airport_id", primary_key: :code, class_name: "Flight"
	has_many :arriving_flights, foreign_key: "arrival_airport_id", primary_key: :code, class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
	has_many :passengers
	belongs_to :flight, optional: true

	accepts_nested_attributes_for :passengers

	def passengers_attributes=(passengers_attributes)
		passengers_attributes.each do |i, passenger_attributes|
			self.passengers.build(passenger_attributes)
		end
	end
end

app/models/flight.rb
class Flight < ApplicationRecord
	belongs_to :departure_airport, primary_key: :code, class_name: "Airport", optional: true
	belongs_to :arrival_airport, primary_key: :code, class_name: "Airport", optional: true
	has_many :bookings
	has_many :passengers, through: :bookings

	validates_length_of :departure_airport, :minimum => 4, :allow_nil => false
	validates_length_of :arrival_airport, :minimum => 4, :allow_nil => false
	validates :icao_id, uniqueness: true

	def self.get_flights(flight_date)
		Opensky.new(flight_date).call
	end

	def self.create_flights(flights, date)
		flights.each do |flight| 
			Flight.create(icao_id: flight['icao24'], 
										departure_airport_id: flight["estDepartureAirport"], 
										arrival_airport_id: flight["estArrivalAirport"], 
										date: date)
			end
	end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
	belongs_to :booking
	validates_presence_of :name, :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	def new
		@booking = Booking.new
		@num_of_passengers = booking_params[:num_of_passengers].to_i

		@num_of_passengers.times do
			@booking.passengers.build
		end

		@selected_flight = Flight.where(icao_id: booking_params[:icao_id]).first || Rails.cache.read("selected_flight") 
		Rails.cache.write("selected_flight", @selected_flight)
		Rails.cache.write("num_of_passengers", @num_of_passengers)
	end

	def create
		@selected_flight = Rails.cache.read("selected_flight") 
		@num_of_passengers = Rails.cache.read("num_of_passengers") 
		@booking = Booking.new(better_params)

		if @booking.save
			@booking.passengers.each do |passenger|
				PassengerMailer.with(passenger: passenger).booking_email.deliver_later
			end
			redirect_to @booking
		else
			render :new, status: :unprocessable_entity
		end
	end

	def show
		@booking = Booking.find(params[:id])
		@selected_flight = @booking.flight
		@passengers = @booking.passengers
		@num_of_passengers = @booking.passengers.count
	end

	private

	def booking_params
		params.require(:booking).permit(:icao_id, :num_of_passengers, passengers_attributes: [:name, :email])
	end

	def better_params
		params.require(:booking).permit(:flight_id, :num_of_passengers, passengers_attributes: [:name, :email])
	end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	helper_method :create

	def show
		@flights = Flight.where(flight_params.except(:num_of_passengers))
		@num_of_passengers = flight_params[:num_of_passengers].to_i
	end

	def new
		#calls method to call API if only dates param is submitted
		create if flight_params.keys.count >= 1

		@flight = Flight.new(flight_params.except(:num_of_passengers))
	end


	def create
		flight_date = flight_params[:date]

		unless Flight.all.exists?(date: flight_date)
			flights = Flight.get_flights(flight_date)
			Flight.create_flights(flights, flight_date)
		end

	end

	private

  def flight_params
		params.fetch(:flight, {}).permit(:date, :departure_airport_id, :arrival_airport_id, :num_of_passengers)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_flightinfo.html.erb
<h1 class="text-center">Flight Info</h1>

<table class="table-auto text-lg">
  <thead>
    <tr>
      <th>Flight #</th>
      <th>Departure Airport</th>
      <th>Arrival Airport</th>
      <th>Departure Date</th>
      <th>Number of Passengers</th>
    </tr>
  </thead>
  <tr>
    <td><%=@selected_flight.icao_id%></td>
    <td><%=@selected_flight.departure_airport.code%> </td>
    <td><%=@selected_flight.arrival_airport.code%> </td>
    <td><%=@selected_flight.date %> </td>
    <td><%=@num_of_passengers%></td>
  </tr>
</table>

app/views/bookings/_form.html.erb
<%= form_with model: @booking, data: { controller: 'passenger', passenger_count_value: @num_of_passengers}, method: :post do |form| %>
    <div data-passenger-target="parent">

      <%= form.fields_for :passengers do |sub_form| %>
        <p> 
          <div id="formRow" class="flex flex-row justify-center">
          <%= sub_form.label :name, "Name:", class:"font-black text-lg content-center mr-3" %>
          <%= sub_form.text_field :name, class:"mr-4" %>
          <%= sub_form.label :email, "Email:", class:"font-black text-lg content-center mr-3" %>
          <%= sub_form.email_field :email %>
          </div>
          <div>
          <% if @booking.errors.any? %>
            <% @booking.errors.each do |message| %>
              <div class="bg-red-300 w-1/2 font-black m-3 rounded"><%= message.full_message %></div>
            <% end %>
          <% end %>
        </div>
        </p>
      <% end %>

      <template data-passenger-target="temp">
        <%= form.fields_for :passengers do |sub_form| %>
          <p id="formRowTemp" class="flex flex-row justify-center align">
            <%= sub_form.label :name, "Name:", class:"font-black text-lg content-center mr-3" %>
            <%= sub_form.text_field :name, class:"mr-4" %>
            <%= sub_form.label :email, "Email:", class:"font-black text-lg content-center mr-3" %>
            <%= sub_form.text_field :email %>
          </p>
        <% end %>
      </template>
    </div>
    <div>

      <button type="button" data-action="passenger#add" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 text-lg px-4 rounded"> Add</button>
      <button type="button" data-action="passenger#remove" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 text-lg rounded"> Remove</button>

      <%= hidden_field_tag 'booking[flight_id]', @selected_flight[:id]  %>
      <%= hidden_field_tag 'booking[num_of_passengers]', @num_of_passengers  %>
      </div>
    <p> <%= form.submit "Book Flight", class:"bg-red-900 hover:bg-red-700 text-white font-bold py-2  rounded text-xl w-1/4 mt-2" %> </p>
<% end %>

app/views/bookings/new.html.erb
<div class="mx-auto border-8 border-slate-300 rounded p-5 bg-white w-3/4">
  <center>
    <%= render 'flightinfo' %>
    <h1 class="text-center">Passenger(s):</h1>
    <%= render 'form' %>
  </center>
</div>

app/views/bookings/show.html.erb
<div class="mx-auto border-8 border-slate-300 rounded p-5 bg-white w-3/4">
	<center>
		<h1> You're Booked! </h1>
		<%= render 'flightinfo' %>

	<h1> Passenger(s) </h1>

	<% @passengers.map do |passenger|%>
		<table class="table-auto text-lg">
			<thead>
			<tr>
		    <th>Name</th>
			  <th>Email</th>
			</tr>
			</thead>
		  <tr>
		    <td><%=passenger.name%></td>
		    <td><%=passenger.email%></td>
		  </tr>
		</table>
	<% end %>
	</center>
</div>

app/views/flights/new.html.erb
<div class="mx-auto border-8 border-slate-300 rounded p-5 bg-white w-2/5">
	<h1 class="text-center">Search Flights</h1>
  <%= form_with model: @flight, url: "/flights/show", method: "get" do |form| %>
  <div class="flex gap-4 flex-col">
    <fieldset class="text-xl flex flex-col text-center gap-2 ">
    	<%= form.label :query, "Travel Date", class:"font-black text-2xl" %>
    	<%= date_field_tag 'flight[date]', value = @flight.date, options = {min: Date.parse("June 1 2023"), max: Date.parse("June 30 2023")} %>
      <button formmethod="get" formaction="<%= new_flight_path %>" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Select</button>
    </fieldset>

    <fieldset class="text-xl flex flex-col text-center gap-2">
    	<%= form.label :query, "Departure Airport", class:"font-black text-2xl"  %>
    	<%= form.select :departure_airport_id, Airport.joins(:departing_flights).where({departing_flights: {date: @flight.date}}).map {|airport| airport.code }.uniq.sort %>
    	<button formmethod="get" formaction="<%= new_flight_path %>" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Select</button>
    </fieldset>

    <fieldset class="text-xl flex flex-col text-center gap-2">
    	<%= form.label :query, "Arrival Airport", class:"font-black text-2xl"  %>
    	<%= form.select :arrival_airport_id, Airport.joins(:arriving_flights).where({arriving_flights: {date: @flight.date, departure_airport: @flight.departure_airport}}).map {|airport| airport.code }.uniq.sort %>
    </fieldset>

    <fieldset class="text-xl flex flex-col text-center gap-2">
    	<%= label_tag(:num_of_passengers, "Number of Passengers", class:"font-black text-2xl" ) %>
    	<%= select_tag  'flight[num_of_passengers]', options_for_select([1, 2, 3, 4]) %>
    </fieldset>

      <%= form.button "Show Flights", class:"bg-red-900 hover:bg-red-700 text-white font-bold py-2 px-4 rounded text-xl"%>
  </div>
  <% end %>
</div>

app/views/flights/show.html.erb
<div class="mx-auto border-8 border-slate-300 rounded p-5 bg-white w-2/5">
	<h1 class="text-center">Available Flights</h1>
	<%= form_with url: "/bookings/new", method: :get do |form| %>
	<div class="flex flex-col">
		<% @flights.map do |flight|%>
			<ul class="flex items-center border-4 px-4 rounded border-slate-400">
				<div>
					<%= radio_button_tag "booking[icao_id]", flight.icao_id%>
					<%= hidden_field_tag 'booking[num_of_passengers]', @num_of_passengers%>
				</div>
				<div class="ml-14 font-black text-lg">
					<li> <%= "Flight Number: #{flight.icao_id}"%> </li>
					<li> <%= "Departure Airport: #{flight.departure_airport.code}"%> </li>
					<li> <%= "Arrival Airport: #{flight.arrival_airport.code}"%> </li>
				</div>
			</ul>
		<% end %>
		<%= form.submit "Select", class:"bg-red-900 hover:bg-red-700 text-white font-bold py-2 px-4 rounded text-xl" %>
	</div>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="prose mx-auto !max-w-none bg-red-950">
    <ul class="flex bg-red-950 justify-center p-2 items-center">
      <%= image_tag("airplane_logo.png", size: "64x40", alt: "Edit Entry", class:"invert") %>
        <a class="text-white text-5xl no-underline tracking-wider ml-4 font-black" <%= link_to "OneWay Vacations", root_path %></a>
    </ul>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>